package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle debug messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link DebugHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface DebugSupplierHandler {

    /**
     * Handles a single debug message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for a debug message to show to the programmer
     * @throws NullPointerException if either {@code messageSupplier} or its production is {@code null}
     */
    void debug(final @Nonnull Supplier<String> messageSupplier);

}
