package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle debug messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link DebugHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface DebugSupplierWithContextHandler {

    /**
     * Handles a single debug message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for a debug message to show to the programmer
     * @param contextInfo          a non-null context in which the debug message was generated
     * @throws NullPointerException if either {@code messageSupplier}, its production, or {@code contextInfo} is {@code null}
     */
    void debug(final @Nonnull Supplier<String> messageSupplier, final @Nonnull ContextInfo contextInfo);

}
