package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle error messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link ErrorHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface ErrorSupplierHandler {

    /**
     * Handles a single error message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for an error message to show to the user
     * @throws NullPointerException if either {@code messageSupplier} or its production is {@code null}
     */
    void error(final @Nonnull Supplier<String> messageSupplier);

}
