package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle error messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link ErrorHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface ErrorSupplierWithContextHandler {

    /**
     * Handles a single error message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for an error message to show to the user
     * @param contextInfo          a non-null context in which the error message was generated
     * @throws NullPointerException if either {@code messageSupplier}, its production, or {@code contextInfo} is {@code null}
     */
    void error(final @Nonnull Supplier<String> messageSupplier, final @Nonnull ContextInfo contextInfo);

}
