package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle fatal messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link FatalHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface FatalSupplierWithContextHandler {

    /**
     * Handles a single fatal message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for a fatal message to show to the user
     * @param contextInfo          a non-null context in which the fatal message was generated
     * @throws NullPointerException if either {@code messageSupplier}, its production, or {@code contextInfo} is {@code null}
     */
    void fatal(final @Nonnull Supplier<String> messageSupplier, final @Nonnull ContextInfo contextInfo);

}
