package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle info messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link InfoHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface InfoSupplierHandler {

    /**
     * Handles a single info message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for an info message to show to the user
     * @throws NullPointerException if either {@code messageSupplier} or its production is {@code null}
     */
    void info(final @Nonnull Supplier<String> messageSupplier);

}
