package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle trace messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link TraceMessageHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface SupplierTraceMessageHandler {

    /**
     * Handles a single trace message generated by a supplier.
     *
     * @param traceMessageSupplier a supplier for a trace message to show to the programmer
     */
    void handleTraceMessage(final @Nonnull Supplier<String> traceMessageSupplier);

}
