package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle info messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link InfoMessageHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface SupplierInfoMessageHandler {

    /**
     * Handles a single info message generated by a supplier.
     *
     * @param infoMessageSupplier a supplier for an info message to show to the user
     */
    void handleInfoMessage(final @Nonnull Supplier<String> infoMessageSupplier);

}
