package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle error messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link ErrorMessageHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface SupplierErrorMessageHandler {

    /**
     * Handles a single error message generated by a supplier.
     *
     * @param errorMessageSupplier a supplier for an error message to show to the user
     */
    void handleErrorMessage(final @Nonnull Supplier<String> errorMessageSupplier);

}
