package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle warn messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link WarnMessageHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface SupplierWarnMessageHandler {

    /**
     * Handles a single warning message generated by a supplier.
     *
     * @param warnMessageSupplier a supplier for a warning message to show to the user
     */
    void handleWarnMessage(final @Nonnull Supplier<String> warnMessageSupplier);

}
