package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle trace messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link TraceHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface TraceSupplierWithContextHandler {

    /**
     * Handles a single trace message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for a trace message to show to the programmer
     * @param contextInfo          a non-null context in which the trace message was generated
     * @throws NullPointerException if either {@code messageSupplier}, its production, or {@code contextInfo} is {@code null}
     */
    void trace(final @Nonnull Supplier<String> messageSupplier, final @Nonnull ContextInfo contextInfo);

}
