package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle trace messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link TraceHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface TraceSupplierHandler {

    /**
     * Handles a single trace message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for a trace message to show to the programmer
     * @throws NullPointerException if either {@code messageSupplier} or its production is {@code null}
     */
    void trace(final @Nonnull Supplier<String> messageSupplier);

}
