package com.threeamigos.common.util.interfaces.messagehandler;

import jakarta.annotation.Nonnull;

import java.util.function.Supplier;

/**
 * An interface used to handle warning messages.<br/>
 * If the message is just a fixed string, you may revert to the simpler {@link WarnHandler}.
 *
 * @author Stefano Reksten
 */
@FunctionalInterface
public interface WarnSupplierHandler {

    /**
     * Handles a single warning message generated by a supplier.
     *
     * @param messageSupplier a non-null supplier for a warning message to show to the user
     * @throws NullPointerException if either {@code messageSupplier} or its production is {@code null}
     */
    void warn(final @Nonnull Supplier<String> messageSupplier);

}
